--INSERT INTO tb_dog (name, breed, age) VALUES ('bob', 'pastor_alemão', '5');
--INSERT INTO tb_doctor (name, identification) VALUES ('jose', 'crm-20321');
--INSERT INTO tb_guardian (name, number) VALUES ('eduardo', '81984493777');